  export const data=[{
    "first_name": "Liuka",
    "last_name": "Barsby",
    "email": "lbarsby0@ed.gov",
    "gender": "Female",
    "date_created": "10/15/2023"
  }, {
    "first_name": "Alastair",
    "last_name": "Armor",
    "email": "aarmor1@utexas.edu",
    "gender": "Male",
    "date_created": "12/6/2022"
  }, {
    "first_name": "Anetta",
    "last_name": "Blackall",
    "email": "ablackall2@mapquest.com",
    "gender": "Non-binary",
    "date_created": "1/11/2023"
  }, {
    "first_name": "Kylen",
    "last_name": "Sclanders",
    "email": "ksclanders3@dailymail.co.uk",
    "gender": "Female",
    "date_created": "5/17/2023"
  }, {
    "first_name": "Robyn",
    "last_name": "Lesley",
    "email": "rlesley4@posterous.com",
    "gender": "Female",
    "date_created": "1/23/2023"
  }, {
    "first_name": "Abey",
    "last_name": "Ferenczy",
    "email": "aferenczy5@home.pl",
    "gender": "Male",
    "date_created": "10/10/2023"
  }, {
    "first_name": "Elston",
    "last_name": "Badham",
    "email": "ebadham6@google.com.au",
    "gender": "Male",
    "date_created": "10/24/2022"
  }, {
    "first_name": "Jesus",
    "last_name": "Britee",
    "email": "jbritee7@bbb.org",
    "gender": "Genderfluid",
    "date_created": "12/16/2022"
  }, {
    "first_name": "Betty",
    "last_name": "Leitch",
    "email": "bleitch8@spotify.com",
    "gender": "Female",
    "date_created": "3/21/2023"
  }, {
    "first_name": "Lauryn",
    "last_name": "Gyves",
    "email": "lgyves9@topsy.com",
    "gender": "Female",
    "date_created": "12/18/2023"
  }, {
    "first_name": "Elna",
    "last_name": "Blesdill",
    "email": "eblesdilla@discuz.net",
    "gender": "Bigender",
    "date_created": "1/14/2024"
  }, {
    "first_name": "Benji",
    "last_name": "Wylam",
    "email": "bwylamb@tamu.edu",
    "gender": "Male",
    "date_created": "9/26/2023"
  }]
  export type User = (typeof data)[number]


